Issue #49, "Programmatic Control of Popup"
dotnet/DataGridExtensions pull request #50
Opened 2021-02-06 14:18 UTC by lieszkol

Please see Issue #49

2021-02-06 14:18 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/DataGridExtensions?pullRequest=50) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/DataGridExtensions?pullRequest=50) before we can accept your contribution.<br/><br/>:x: lieszkol [sign now](https://cla.dotnetfoundation.org/dotnet/DataGridExtensions?pullRequest=50)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/DataGridExtensions?pullRequest=50) it.</sub>

2021-02-21 09:00 UTC, tom-englert requested changes

2021-02-22 09:55 UTC, lieszkol commented on src/DataGridExtensions/DataGridFilterColumnControl.cs
> +        public bool IsPopupVisible
And then do something like this in the viewmodel:

```
            if (Column5FilterColumnControl.FilterControl is FilterWithPopupControl filterWithPopupControl)
            {
                filterWithPopupControl.IsPopupVisible = true;
            }
```

?

I think it's more cumbersome for the end-user than writing `Column5FilterColumnControl.IsPopupVisible = true` but it works, I will make the required changes and update the PR.

2021-02-22 10:01 UTC, lieszkol commented on src/DataGridExtensionsSample/Controls/FilterWithPopupControl.xaml.cs
> +        private string caption;
Ok, I will make the changes and update the PR.

2021-03-06 17:08 UTC, tom-englert approved these changes

2021-03-06 17:08 UTC, tom-englert commented
👍 😄

2021-03-06 17:08 UTC, merged