Fix multiple choice filter
dotnet/DataGridExtensions pull request #64
Opened 2021-05-19 22:16 UTC by grizoood

Hello,

Here is the pull request for the issue: # 62

2021-05-19 22:16 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/DataGridExtensions?pullRequest=64) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/DataGridExtensions?pullRequest=64) before we can accept your contribution.<br/><br/>:x: grizoood [sign now](https://cla.dotnetfoundation.org/dotnet/DataGridExtensions?pullRequest=64)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/DataGridExtensions?pullRequest=64) it.</sub>

2021-05-20 10:22 UTC, tom-englert requested changes

2021-05-20 10:22 UTC, tom-englert commented on src/DataGridExtensionsSample/Views/Customized2View.xaml
> +    <UserControl.Resources>
90% of this PR is just reformatting the code. Please stick with the existing formatting.

2021-05-20 12:50 UTC, tom-englert approved these changes

2021-05-20 12:51 UTC, merged

2021-05-20 12:52 UTC, tom-englert commented
Fixes #62